# Generated by Django 3.2.3 on 2021-05-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('content', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('WAITING', 'Waiting'), ('FINISHED', 'Finished')], default='NEW', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='info@kayaccountingclinic.com', max_length=254)),
                ('phone', models.CharField(default='+234-803-4556-488', max_length=22)),
                ('address', models.CharField(default='some address, Lagos Nigeria', max_length=100)),
                ('facebook', models.URLField(default='www.facebook.com')),
                ('instagram', models.URLField(default='www.instagram.com')),
                ('linkedin', models.URLField(default='www.linkedin.com')),
                ('twitter', models.URLField(default='www.twitter.com')),
            ],
        ),
    ]
