# Generated by Django 3.2.3 on 2021-05-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_instance_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contactmessage',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['NEW', 'WAITING', 'FINISHED'])), name='main_ContactMessage_status_valid'),
        ),
    ]
