# Generated by Django 3.2.3 on 2021-05-28 16:49

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactmessage_main_contactmessage_status_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_sent', models.DateTimeField(default=main.utils.current_time)),
            ],
        ),
    ]
