# Generated by Django 3.2.3 on 2021-06-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com', help_text='Add http or https to the url'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='instagram',
            field=models.URLField(default='https://www.instagram.com', help_text='Add http or https to the url'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='linkedin',
            field=models.URLField(default='https://www.linkedin.com', help_text='Add http or https to the url'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='phone',
            field=models.CharField(default='+2347011540697', max_length=22),
        ),
        migrations.AlterField(
            model_name='instance',
            name='twitter',
            field=models.URLField(default='https://www.twitter.com', help_text='Add http or https to the url'),
        ),
    ]
